app/cart/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name='cart_detail'),
    path('increase-quantity/<pk>/',
         views.IncreaseQuantityView.as_view(), name='increase-quantity'),
    path('decrease-quantity/<pk>/',
         views.DecreaseQuantityView.as_view(), name='decrease-quantity'),
    path('remove-from-cart/<pk>/',
         views.RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('checkout/', login_required(views.CheckoutView.as_view()), name='checkout'),
    path('payment/', login_required(views.PaymentView.as_view()), name='payment'),
    path('thanks/', views.ThankYouView.as_view(), name='thanks'),
]

app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('users/', include('perfiles.urls', namespace='perfiles')),
    path('products/', include('products.urls', namespace='products')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/perfiles/urls.py
from django.contrib.auth import views
from django.urls import path

from . import views
from .views import UserProfileView

app_name = "perfiles"

urlpatterns = [
    path("addresses/", views.view_address, name="direcciones"),
    path("add_address/", views.add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"),
    path("addresses/delete/<slug:id>/",
         views.delete_address, name="delete_address"),
    path("addresses/set_default/<slug:id>/",
         views.set_default, name="set_default"),
    path("edit_profile/", views.edit_profile, name="edit_profile"),
    path('<username>/', UserProfileView.as_view(), name="perfil")
]

app/store/urls.py
from django.urls import path

from .views import CategoryListView, DetalleView, HomeView

app_name = 'store'

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('<slug:slug>/', DetalleView.as_view(), name="detail"),
    path('<slug:category_slug>/',
         CategoryListView.as_view(), name="category_list"),
]

app/cart/models.py
from decimal import Decimal

from django.db import models
from perfiles.models import Address, UserBase
from store.models import Articulo


class Order(models.Model):
    user = models.ForeignKey(
        UserBase, on_delete=models.CASCADE, blank=True, null=True)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField(
        auto_now_add=True, blank=True, null=True)
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey(
        Address, related_name='dir_facturacion', blank=True, null=True, on_delete=models.SET_NULL)
    shipping_address = models.ForeignKey(
        Address, related_name='dir_envio', blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.reference_number

    @property
    def reference_number(self):
        return f"ORDER-{self.pk}"

    def get_raw_subtotal(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_total_item_price()
        return total

    def get_subtotal(self):
        subtotal = self.get_raw_subtotal() - self.get_impuesto()
        return subtotal

    def get_impuesto(self):
        valor_impuesto = 16
        impuesto = self.get_raw_subtotal() * valor_impuesto / 100
        return impuesto

    def get_raw_total(self):
        subtotal = self.get_raw_subtotal()
        # agregar suma de IGV, Delivery, Resta DESCUENTOS
        #total = subtotal - discounts + tax + delivery
        return subtotal

    def get_total(self):
        total = self.get_raw_total()
        return total


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Articulo, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} x {self.product.title}"

    def get_raw_total_item_price(self):
        if self.product.product.discount_price:
            precio_producto = self.product.product.discount_price
        else:
            precio_producto = self.product.product.store_price

        return self.quantity * precio_producto

    def get_total_item_price(self):
        price = self.get_raw_total_item_price()
        return price


class Payment(models.Model):
    order = models.OneToOneField(
        Order, on_delete=models.PROTECT, related_name='payments')
    payment_method = models.CharField(
        max_length=20, choices=(('Paypal', 'Paypal'),))
    timestamp = models.DateTimeField(auto_now_add=True)
    succesful = models.BooleanField(default=False)
    amount = models.FloatField()
    raw_response = models.TextField()

    def __str__(self):
        return self.reference_number

    @property
    def reference_number(self):
        return f"PAYMENT-{self.order}-{self.pk}"

app/cart/forms.py
from django import forms

from .models import OrderItem

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class AddToCartForm(forms.ModelForm):
    # attributes = forms.ChoiceField()
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput)

    class Meta:
        model = OrderItem
        fields = ['quantity', 'override']

app/cart/views.py
import datetime
import json

from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views import generic
from perfiles.forms import UserAddressForm
from perfiles.models import Address
from store.models import Articulo

from .cart import get_or_set_order_session
from .models import OrderItem, Payment


class CartView(generic.TemplateView):
    template_name = 'cart/detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(CartView, self).get_context_data(**kwargs)
        context["order"] = get_or_set_order_session(self.request)
        cart = context["order"]
        context["post"] = cart.items.all()
        return context


def cart_remove(request, product_id):
    cart = get_or_set_order_session(request)
    product = get_object_or_404(Articulo, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


class CheckoutView(generic.FormView):
    template_name = 'cart/checkout.html'
    form_class = UserAddressForm

    """ def get_success_url(self):
        return reverse("cart:pyment") """

    """ def get_form_kwargs(self):
        kwargs = super(CheckoutView, self).get_form_kwargs()
        kwargs["user_id"] = self.request.user.id
        return kwargs """

    def get_context_data(self, *args, **kwargs):
        addresses = Address.objects.filter(user=self.request.user)
        addr_default = False
        for addr in addresses:
            if addr.default:
                addr_default = True

        context = super(CheckoutView, self).get_context_data(**kwargs)
        context['order'] = get_or_set_order_session(self.request)
        context['addresses'] = addresses
        context['addr_default'] = addr_default
        return context


class IncreaseQuantityView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        order_item.quantity += 1
        order_item.save()
        return redirect("cart:cart_detail")


class DecreaseQuantityView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])

        if order_item.quantity <= 1:
            order_item.delete()
        else:
            order_item.quantity -= 1
            order_item.save()
        return redirect("cart:cart_detail")


class RemoveFromCartView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        order_item.delete()
        return redirect("cart:cart_detail")


class PaymentView(generic.TemplateView):
    template_name = 'cart/payment.html'

    def get_context_data(self, **kwargs):
        context = super(PaymentView, self).get_context_data(**kwargs)
        # context["PAYPAL_CLIENT_ID"] = settings.PAYPAL_CLIENT_ID
        context['order'] = get_or_set_order_session(self.request)
        context['CALLBACK_URL'] = self.request.build_absolute_uri(
            reverse("cart:thanks"))
        return context


class ConfirmOrderView(generic.View):
    def post(self, request, *args, **kwargs):
        order = get_or_set_order_session(request)
        body = json.loads(request.body)
        payment = Payment.objects.create(
            order=order,
            successful=True,
            raw_response=json.dumps(body),
            amount=float(body["purchase_units"][0]["amount"]["value"]),
            payment_method='PayPal'
        )
        order.ordered = True
        order.ordered_date = datetime.date.today()
        order.save()
        return JsonResponse({"data": "Success"})


class ThankYouView(generic.TemplateView):
    template_engine = 'cart/thanks.html'

app/templates/cart/checkout.html
{% extends 'base.html' %}
{% load humanize %}
{% load crispy_forms_tags %}

{% block head_title %}
  CheckOut
{% endblock head_title %}

{% block content %}
	<div class="bg-light py-3">
		<div class="container">
			<div class="row">
				<div class="col-md-12 mb-0">
					<a href="/">Home</a><span class="mx-2 mb-0">/</span>
					<a href="{% url 'cart:cart_detail' %}">Cart</a><span class="mx-2 mb-0">/</span>
					<strong class="text-block">CheckOut</strong>
				</div>
			</div>
		</div>
	</div>
	<div class="container py-3">
		<div class="row">
			<div class="col-md-6 mb-md-0">
				<h2 class="h3 mb-3 text-black text-center">dirección de envío</h2>
				<hr />
				<div>
					{% for address in addresses %}
						{% if address.default %}
							<div class="col-12">
								<div class="card">
									<div class="card-body small mx-5 pb-1">
										<dl class="row">
											<dt class="col-sm-4">Residencia:</dt>
											<dd class="col-sm-8">
												{{address.shipping_address}}
											</dd>
											{% if address.billing_address %}
												<dt class="col-sm-4">Oficina:</dt>
												<dd class="col-sm-8">
													{{address.billing_address}}
												</dd>
											{% endif %}
											<dt class="col-sm-4">Ciudad:</dt>
											<dd class="col-sm-8">
												{{address.ciudad}}
											</dd>
											<dt class="col-sm-4">Departamento:</dt>
											<dd class="col-sm-8">
												{{address.departamento}}
											</dd>
											<dt class="col-sm-4">Zip code:</dt>
											<dd class="col-sm-8">
												{{address.zip}}
											</dd>
										</dl>
									</div>
								</div>
							</div>
						{% endif %}
					{% empty %}
						<div class="text-center">
							<p class="text-danger">Aún no has configurado una dirección de envío por defecto, click en el siguente enlace <br/><a href="{% url 'perfiles:direcciones' %}" type="button">configurar direccion de envío</a><br/> y agrega una dirección de envío</p>
						</div>
					{% endfor %}
				</div>
				<div class="p-3 p-lg-4">
					<a href="{% url 'cart:cart_detail' %}" class="btn btn-warning btn-lg" tabindex="-1" role="button">
						Regresar al Carrito
					</a>
					{% if addr_default %}
						<a href="{% url 'cart:payment' %}" class="btn btn-success btn-lg" tabindex="-1" role="button">
							Continuar con el Pago
						</a>
					{% else %}
						<a class="btn btn-primary btn-lg disabled" tabindex="-1" role="button">
							Continuar con el Pago
						</a>
					{% endif %}
				</div>
				<div class="p-2 p-lg-2">
					<a href="{% url 'perfiles:direcciones' %}">cambiar o agregar dirección de envío por defecto</a>
				</div>
			</div>
			<div class="col-md-6">
				<div class="row">
					<div class="col-md-12">
						<h2 class="h3 mb-3 text-black text-center">Detalle del pedido</h2>
						<hr>
						<div class="p-2 p-lg-3">
							<table class="table site-block-order-table">
								<thead>
									<th>Product</th>
									<th>Total</th>
								</thead>
								<tbody>
									{% for item in order.items.all %}
										<tr>
											<td>
												{{ item.product.title }}
												<strong class="mx-2">x</strong> {{ item.quantity }}
											</td>
											<td>
												$ {{ item.get_total_item_price|intcomma }}
											</td>
										</tr>
									{% endfor %}
										<tr class="total">
											<th>Subtotal</th>
											<th>$ {{ order.get_subtotal|intcomma }}</th>
										</tr>
										<tr class="total">
											<th>Impuesto (IVA 16%)</th>
											<th>$ {{ order.get_impuesto|intcomma }}</th>
										</tr>
										<tr class="total">
											<th><strong>Order Total</strong></th>
											<th>$ {{ order.get_total|intcomma }}</th>
										</tr>
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div> <!-- /row -->
	</div> <!-- /container -->
{% endblock content %}

app/templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load crispy_forms_tags %}

{% load i18n %}
{% block head_title %}
  Shopping Cart
{% endblock head_title %}

{% block content %}
  <div class = "container pb-3">
    <h1>Shopping Cart</h1>
    <div class="table-responsive">
      <table class='table align-middle'>
        <thead>
          <tr class="text-center">
            <th>Imágen</th>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Acciones</th>
            <th>Precio Unidad</th>
            <th>Total</th>
          </tr>
        </thead>
        <tbody>
          {% for item in post %}
            <tr class="text-center">
              <td>
                <a href="{{ item.product.get_absolute_url }}">
                  <img height="35" src="{{ item.product.img.url }}">
                </a>
              </td>
              <td> {{ item.product.title }} </td>
              <td>
                <div class="input-group" style="max-width: 150px;">
                  <a href="{% url 'cart:decrease-quantity' item.id %}" class="btn btn-outline-primary" type="button">&minus;</a>
                  <input type="text" class="form-control text-center" value="{{ item.quantity }}">
                  <a href="{% url 'cart:increase-quantity' item.id %}" class="btn btn-outline-primary" type="button">&plus;</a>
                </div>
              </td>
              <td>
                <a href="{% url 'cart:remove-from-cart' item.id %}" class="btn btn-danger btn-sm">Eliminar</a>
              </td>
              <td>$ {{ item.product.product.get_price|intcomma }}</td>
              <td>$ {{ item.get_total_item_price|intcomma }}</td>
            </tr>
          {% empty %}
            <tr>
              <td colspan="6">
                <div class="alert alert-warning">
                  No has agregado productos a tu carrito de compras. <a href="{% url 'store:home' %}">Ver productos</a>
                </div>
              </td>
            </tr>
          {% endfor %}
          {% if post %}
            <tr class="total">
              <td colspan="4"></td>
              <th>Total</th>
              <th>$ {{ order.get_total|intcomma }}</th>
            </tr>
          {% else %}

          {% endif %}
        </tbody>
      </table>
    </div>
    <p class="text-right">
      <a href="{% url 'store:home' %}" class="btn btn-primary">Seguir Comprando</a>
      <a href="{% url 'cart:checkout' %}" class="btn btn-warning">Verificar Compra</a>
    </p>
  </div>
{% endblock content %}

app/templates/cart/payment.html
{% extends 'base.html' %}
{% load humanize %}

{% block head_title %}
  Payment
{% endblock head_title %}

{% block content %}
  <style>
.lds-ring {
  display: inline-block;
  position: relative;
  width: 80px;
  height: 80px;
}
.lds-ring div {
  box-sizing: border-box;
  display: block;
  position: absolute;
  width: 64px;
  height: 64px;
  margin: 8px;
  border: 8px solid rgb(155, 81, 81);
  border-radius: 50%;
  animation: lds-ring 1.2s cubic-bezier(0.5, 0, 0.5, 1) infinite;
  border-color: rgb(155, 81, 81) transparent transparent transparent;
}
.lds-ring div:nth-child(1) {
  animation-delay: -0.45s;
}
.lds-ring div:nth-child(2) {
  animation-delay: -0.3s;
}
.lds-ring div:nth-child(3) {
  animation-delay: -0.15s;
}
@keyframes lds-ring {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}

</style>


<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">

      {% comment %} <div class="alert alert-success" role="alert" id="alertSuccess" style="display: none;">
        Your payment was successful.
      </div>
      <div class="alert alert-danger" role="alert" id="alertFailure" style="display: none;">
        Your payment failed. Please try again.
      </div>
      <div class="text-center py-3">
        <div id="loader" class="lds-ring" style="margin:auto; display:none;">
          <div></div>
          <div></div>
          <div></div>
          <div></div>
        </div>
      </div> {% endcomment %}

      <div id='paymentInfo'>
        <p class="h5">Total pedido: $ {{ order.get_total|intcomma }}</p>
        <h4>Seleccione el método de pago</h4>
        <div id="paypal-button-container"></div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block scripts %}
  <script src="https://www.paypal.com/sdk/js?client-id=125487"></script>
  <script>
    paypal.Buttons({
      createOrder: function(data, actions) {
        return actions.order.create({
          purchase_units: [{
          amount: {
            value: '0.01'
          }
          }]
        });
      },
      onApprove: function(data, actions) {
        return actions.order.capture().then(function(details) {
          alert('Transaction completed by ' + details.payer.name.given_name);
        });
      }
    }).render('#paypal-button-container');
  </script>
{% endblock scripts %}

app/templates/cart/thankyou.html
{% extends 'base.html' %}

{% block head_title %}
  Agradecimiento
{% endblock head_title %}

{% block content %}
  <h1>Gracias por tu compra</h1>
{% endblock content %}