app/cart/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name='cart_detail'),
    path('increase-quantity/<pk>/',
         views.IncreaseQuantityView.as_view(), name='increase-quantity'),
    path('decrease-quantity/<pk>/',
         views.DecreaseQuantityView.as_view(), name='decrease-quantity'),
    path('remove-from-cart/<pk>/',
         views.RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('checkout/', login_required(views.CheckoutView.as_view()), name='checkout'),
    path('payment/', login_required(views.PaymentView.as_view()), name='payment'),
    path('thanks/', views.ThankYouView.as_view(), name='thanks'),
]

app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('users/', include('perfiles.urls', namespace='perfiles')),
    path('products/', include('products.urls', namespace='products')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/products/urls.py
from django.urls import path

from .views import ProductListView, MediaDetailView

app_name = "products"

urlpatterns = [
    path("<int:pk>", MediaDetailView.as_view(), name="media_detail"),
    path("", ProductListView.as_view(), name="products"),
]

app/products/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from inventario.models import Inventory
from mptt.models import MPTTModel, TreeForeignKey, TreeManyToManyField


class Category(MPTTModel):

    name = models.CharField(
        max_length=100,
        null=False,
        unique=False,
        blank=False,
        verbose_name=_("nombre de categoria"),
        help_text=_("format: required, max-100"),
    )
    slug = models.SlugField(
        max_length=150,
        null=False,
        unique=False,
        blank=False,
        verbose_name=_("slug"),
        help_text=_(
            "format: required, letters, numbers, underscore, or hyphens"
        ),
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name=_("activo"),
        help_text=_("format: true=category visible"),
    )

    parent = TreeForeignKey(
        "self",
        on_delete=models.PROTECT,
        related_name="children",
        null=True,
        blank=True,
        unique=False,
        verbose_name=_("categoria padre"),
        help_text=_("format: not required"),
    )

    """ def get_absolute_url(self):
        return reverse("store:category_list", args=[self.slug]) """

    class MPTTMeta:
        order_insertion_by = ["name"]

    class Meta:
        verbose_name = _("categoria")
        verbose_name_plural = _("product categories")

    def __str__(self):
        return self.name


class Brand(models.Model):

    name = models.CharField(
        max_length=255,
        unique=True,
        null=False,
        blank=False,
        verbose_name=_("nombre de marca"),
        help_text=_("format: required, unique, max-255"),
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name=_("brand visibility"),
        help_text=_("format: true=brand visible"),
    )

    def __str__(self):
        return self.name


class Type(models.Model):

    name = models.CharField(
        max_length=255,
        unique=True,
        null=False,
        blank=False,
        verbose_name=_("tipo de producto"),
        help_text=_("format: required, unique, max-255"),
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name=_("producto activo"),
        help_text=_("format: true=product visible"),
    )

    def __str__(self):
        return self.name


class Attribute(models.Model):

    name = models.CharField(
        max_length=255,
        unique=True,
        null=False,
        blank=False,
        verbose_name=_("product attribute name"),
        help_text=_("format: required, unique, max-255"),
    )
    description = models.TextField(
        unique=False,
        null=False,
        blank=False,
        help_text=_("format: required"),
    )

    def __str__(self):
        return self.name


class AttributeValue(models.Model):

    attribute = models.ForeignKey(
        Attribute,
        related_name="attribute",
        on_delete=models.PROTECT,
    )
    attribute_value = models.CharField(
        max_length=255,
        unique=False,
        null=False,
        blank=False,
        verbose_name=_("attribute value"),
        help_text=_("format: required, max-255"),
    )

    def __str__(self):
        return f"{self.attribute.name} : {self.attribute_value}"


class Product(models.Model):

    name = models.CharField(
        max_length=255,
        unique=False,
        null=False,
        blank=False,
        verbose_name=_("nombre"),
        help_text=_("format: required, max-255"),
    )
    slug = models.SlugField(
        max_length=255,
        unique=False,
        null=False,
        blank=False,
        verbose_name=_("Slug"),
        help_text=_(
            "format: required, letters, numbers, underscores or hyphens"
        ),
    )
    web_id = models.CharField(
        max_length=50,
        unique=True,
        null=False,
        blank=False,
        verbose_name=_("ID Web"),
        help_text=_("numero de referencia"),
    )
    inventory = models.ForeignKey(
        Inventory, related_name="products", on_delete=models.CASCADE, null=True, blank=True
    )
    category = TreeManyToManyField(Category, verbose_name="category")
    brand = models.ForeignKey(
        Brand, related_name=_("brand"), on_delete=models.PROTECT
    )
    type = models.ForeignKey(
        Type, verbose_name=_("Product Type"), on_delete=models.CASCADE)
    attribute = models.ManyToManyField(
        Attribute, related_name=_("attributes"))
    description = models.TextField(
        unique=False,
        null=False,
        blank=False,
        verbose_name=_("descripcion"),
        help_text=_("format: required"),
    )
    retail_price = models.DecimalField(
        max_digits=9,
        decimal_places=2,
        unique=False,
        null=False,
        blank=False,
        verbose_name=_("precio al detalle"),
        help_text=_("format: maximum price 9.999.999.99"),
        error_messages={
            "name": {
                "max_length": _("the price must be between 0 and 9.999.999.99."),
            },
        },
    )
    store_price = models.DecimalField(
        max_digits=9,
        decimal_places=2,
        unique=False,
        null=False,
        blank=False,
        verbose_name=_("precio regular"),
        help_text=_("format: maximum price 9.999.999.99"),
        error_messages={
            "name": {
                "max_length": _("the price must be between 0 and 9.999.999.99."),
            },
        },
    )
    percent_discount_price = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        unique=False,
        null=True,
        blank=True,
        verbose_name=_("descuento %"),
        help_text=_("format: maximum value 99.99"),
        error_messages={
            "name": {
                "max_length": _("the value must be between 0 and 99.99."),
            },
        },
    )
    discount_price = models.DecimalField(
        max_digits=9,
        decimal_places=2,
        unique=False,
        null=True,
        blank=True,
        verbose_name=_("precio oferta"),
        help_text=_("format: maximum price 9.999.999.99"),
        error_messages={
            "name": {
                "max_length": _("the price must be between 0 and 9.999.999.99."),
            },
        },
    )
    weight = models.FloatField(
        unique=False,
        null=False,
        blank=False,
        verbose_name=_("peso del producto"),
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name=_("activo"),
        help_text=_("format: true=product visible"),
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        editable=False,
        verbose_name=_("fecha creacion"),
        help_text=_("format: Y-m-d H:M:S"),
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name=_("actualizado"),
        help_text=_("format: Y-m-d H:M:S"),
    )

    def get_absolute_url(self):
        return reverse("product:product_detail", kwargs={"pk": self.pk})

    def get_categories(self):
        return ', '.join([str(c) for c in self.category.all()])

    def get_price(self):
        if self.discount_price:
            return self.discount_price
        else:
            return self.store_price

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created_at',)

    def __str__(self):
        return self.name


class Media(models.Model):

    image = models.ImageField(
        unique=False,
        null=False,
        blank=False,
        verbose_name=_("imagen"),
        upload_to="images/",
        default="images/default.png",
        help_text=_("format: required, default-default.png"),
    )
    alt_text = models.CharField(
        max_length=255,
        unique=False,
        null=False,
        blank=False,
        verbose_name=_("texto alternativo"),
        help_text=_("format: required, max-255"),
    )
    product = models.ForeignKey(
        Product, related_name='imagenes', on_delete=models.CASCADE)
    is_featured = models.BooleanField(
        default=False,
        verbose_name=_("destacado"),
        help_text=_("format: default=false, true=default image"),
    )
    default = models.BooleanField(
        default=False,
        verbose_name=_("por defecto"),
        help_text=_("format: default=false, true=default image"),
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        editable=False,
        verbose_name=_("creado desde"),
        help_text=_("format: Y-m-d H:M:S"),
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name=_("actualizado"),
        help_text=_("format: Y-m-d H:M:S"),
    )

    def get_absolute_url(self):
        return reverse("products:products/product_detail", args=[self.slug])

    class Meta:
        verbose_name = _("product image")
        verbose_name_plural = _("product images")
        ordering = ('created_at',)

    def __str__(self):
        return self.alt_text

app/products/views.py
from itertools import product
from django.shortcuts import render
from django.views import generic

from .models import Product, Media

namespace = "products"


class ProductListView(generic.ListView):

    model = Product

    def get(self, request):
        products = Product.objects.all()
        products_images = products.filter(imagenes__default=True)

        context = {
            "products": products,
            "images": products_images,
        }

        return render(request, "products/product_list.html", context)


class MediaDetailView(generic.DetailView):

    model = Product
    template_name = "products/product_detail.html"

app/templates/products/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load crispy_forms_tags %}

{% load i18n %}
{% block head_title %}

  {{ object.name }} {% if user.is_authenticated %} - {{ user.username }} {% endif %}
{% endblock head_title %}

{% block content %}
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">
      <div class="row d-flex justify-content-center wow fadeIn">
        <div class="card h-100 mb-3 ml-10" style="">
          <div class="row g-0">
            <div class="col-md-5 d-flex justify-content-end">
              <img
                src=""
                alt=""
                class="img-fluid"
              />
            </div>
            <div class="col-md-7 d-flex align-self-center">
              <div class="card-body">
                <div class="mb-3 mx-4">
                  <a href="">
                    <span class="badge  bg-warning mr-1">{{ object.get_categories }}</span>
                    <span class="badge  bg-{{ item.get_label_display }} bg-danger">{% translate "NEW" %}</span>
                  </a>
                  <p class="lead">
                    {% if object.discount_price %}
                    <span class="me-3">
                      <del>${{ object.store_price|intcomma }}</del>
                    </span>
                    <span>${{ object.discount_price|intcomma }}</span>
                    {% else %}
                    <span>${{ object.store_price|intcomma }}</span>
                    {% endif %}
                  </p>

                  <h5 class="card-title">{% translate "Description" %}</h5>
                  <p class="card-text">
                    {{ object.description }}
                  </p>
                  <form  method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}

                    <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
                      {% translate "Add to cart" %}
                      <i class="fas fa-shopping-cart ml-1"></i>
                    </a>
                    <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
                      {% translate "Remove from cart" %}
                    </a>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
{% endblock content %}

app/templates/products/product_list.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load humanize %}

{% block head_title %}
  {% if user.is_authenticated %}
    {% translate "Products list" %} - {{ user.username }}
  {% else %}
    {% translate "Products list" %}
  {% endif %}
{% endblock head_title %}

{% block left_sidebar %}
  {% include 'components/sidebars/left/sidebar.html' %}
{% endblock left_sidebar %}

{% block content %}
  <main>
    <!-- Carousel wrapper -->
    {% comment %} {% include 'carousel.html' %} {% endcomment %}
    <!-- Carousel wrapper -->

    <section style="background-color: #eeefff;" class="">
      <div class="container">
        <div class="d-flex justify-content-start align-items-center">
          <h2>Productos</h2>
          <a class="mx-3" href="#">Ver todos</a>
        </div>
        {% if products %}
          <div class="row">
            {% for product in products %}
              <div class="col-md-3 col-lg-2 mb-4">
                <div class="card h-100">
                  <a href="{% url 'products:media_detail' product.id %}">

                    <img
                      src="{{ product.imagenes.first.image.url }}"
                      class="card-img-top"
                      alt="{{ product.imagenes.first.alt_text }}"
                    />

                  </a>

                  <div class="card-body d-flex align-items-end">
                    <p class="card-text">

                    </p>
                    <p class="card-text">
                      {{ product.description }}
                    </p>
                  </div>
                  <div class="card-footer d-flex">
                    <a href="{{ media.get_absolute_url }}">
                      <h5 class="card-title">{{ product.name }}</h5>
                    </a>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div> <!-- /row -->
        {% else %}
          <p class="alert alert-info">No hay productos disponibles!</p>
        {% endif %}
      </div>
    </section>
  </main>
{% endblock content %}