app/cart/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name='cart_detail'),
    path('increase-quantity/<pk>/',
         views.IncreaseQuantityView.as_view(), name='increase-quantity'),
    path('decrease-quantity/<pk>/',
         views.DecreaseQuantityView.as_view(), name='decrease-quantity'),
    path('remove-from-cart/<pk>/',
         views.RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('checkout/', login_required(views.CheckoutView.as_view()), name='checkout'),
    path('payment/', login_required(views.PaymentView.as_view()), name='payment'),
    path('thanks/', views.ThankYouView.as_view(), name='thanks'),
]

app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('users/', include('perfiles.urls', namespace='perfiles')),
    path('products/', include('products.urls', namespace='products')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/perfiles/urls.py
from django.contrib.auth import views
from django.urls import path

from . import views
from .views import UserProfileView

app_name = "perfiles"

urlpatterns = [
    path("addresses/", views.view_address, name="direcciones"),
    path("add_address/", views.add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"),
    path("addresses/delete/<slug:id>/",
         views.delete_address, name="delete_address"),
    path("addresses/set_default/<slug:id>/",
         views.set_default, name="set_default"),
    path("edit_profile/", views.edit_profile, name="edit_profile"),
    path('<username>/', UserProfileView.as_view(), name="perfil")
]

app/perfiles/models.py
import os
import uuid
from pathlib import Path

from django.conf import settings
from django.contrib import admin
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin)
from django.core.mail import send_mail
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _
from django_countries.fields import CountryField
from djchoices import ChoiceItem, DjangoChoices
from djchoices.choices import ChoiceItem

BASE_DIR = Path(__file__).resolve().parent.parent


def user_directory_path_profile(instance, filename):
    profile_picture_name = 'users/{0}/profile.jpg'.format(
        instance.user.username)
    full_path = os.path.join(settings.MEDIA_ROOT, profile_picture_name)
    """ full_path = str(BASE_DIR.joinpath(
        settings.MEDIA_ROOT, profile_picture_name)) """

    if os.path.exists(full_path):
        os.remove(full_path)

    return profile_picture_name


def user_directory_path_banner(instance, filename):
    profile_picture_name = 'users/{0}/banner.jpg'.format(
        instance.user.username)
    full_path = os.path.join(settings.MEDIA_ROOT, profile_picture_name)
    """ full_path = str(BASE_DIR.joinpath(
        settings.MEDIA_ROOT, profile_picture_name)) """

    if os.path.exists(full_path):
        os.remove(full_path)

    return profile_picture_name


class CustomAccountManager(BaseUserManager):

    def create_superuser(self, email, username, password, **other_fields):

        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)

        if other_fields.get('is_staff') is not True:
            raise ValueError(
                'Superuser must be assigned to is_staff=True.')
        if other_fields.get('is_superuser') is not True:
            raise ValueError(
                'Superuser must be assigned to is_superuser=True.')

        return self.create_user(email, username, password, **other_fields)

    def create_user(self, email, username, password, **other_fields):

        if not email:
            raise ValueError(_('You must provide an email address'))

        email = self.normalize_email(email)
        user = self.model(email=email, username=username,
                          **other_fields)
        user.set_password(password)
        user.save()
        return user


class UserBase(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(_('email address'), unique=True)
    username = models.CharField(max_length=150, unique=True)
    first_name = models.CharField(max_length=150, blank=True)
    last_name = models.CharField(max_length=150, blank=True)

    # User Status
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = CustomAccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        verbose_name = "Accounts"
        verbose_name_plural = "Accounts"

    def email_user(self, subject, message):
        send_mail(
            subject,
            message,
            'l@1.com',
            [self.email],
            fail_silently=False,
        )

    def __str__(self):
        return self.username


class GenderType(DjangoChoices):
    male = ChoiceItem('male', 'Hombre')
    female = ChoiceItem('female', 'Mujer')


class VerificationType(DjangoChoices):
    unverified = ChoiceItem('unverified', 'No verificado')
    verified = ChoiceItem('verified', 'Verificado')


class Profile(models.Model):

    user = models.OneToOneField(
        UserBase, on_delete=models.CASCADE, related_name='profile')
    picture = models.ImageField(
        default='users/user_default_profile.png', upload_to=user_directory_path_profile)
    banner = models.ImageField(
        default='users/user_default_bg.jpg', upload_to=user_directory_path_banner)
    gender = models.CharField(
        max_length=10, choices=GenderType.choices, default=GenderType.male)
    verified = models.CharField(
        max_length=10, choices=VerificationType, default=VerificationType.unverified)
    url = models.CharField(max_length=80, null=True, blank=True)
    birthday = models.DateField(null=True, blank=True)
    bio = models.TextField(max_length=150, null=True, blank=True)
    phone = models.CharField(max_length=50)
    mobile = models.CharField(max_length=50, null=True, blank=True)

    class Meta:
        verbose_name = 'Usuario'

    def __str__(self):
        return self.user.username


class AddressType(DjangoChoices):
    B = ChoiceItem('Billing')
    S = ChoiceItem('Shipping')


class Address(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(UserBase, on_delete=models.CASCADE)
    shipping_address = models.CharField(
        max_length=150, verbose_name='Dirección de envío')
    billing_address = models.CharField(
        max_length=150, verbose_name='Dirección de facturacion')
    pais = CountryField(multiple=False)
    departamento = models.CharField(max_length=100)
    ciudad = models.CharField(max_length=100)
    zip = models.CharField(
        max_length=100, verbose_name='Zip code')
    address_type = models.CharField(
        max_length=8, choices=AddressType.choices, default=AddressType.S)
    default = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.shipping_address}, {self.billing_address}, {self.ciudad}, {self.zip}"

    class Meta:
        verbose_name = 'Direccion'
        verbose_name_plural = 'Direcciones'


@receiver(post_save, sender=UserBase)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=UserBase)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

app/perfiles/forms.py
import datetime

from django import forms
from django.forms.widgets import NumberInput

from .models import Address, Profile, UserBase


class UserAddressForm(forms.ModelForm):

    class Meta:
        model = Address
        fields = ["shipping_address",
                  "billing_address", "ciudad", "departamento", "zip"]

    def __init__(self, *args, **kwargs):
        # user_id = kwargs.pop('user_id')
        super().__init__(*args, **kwargs)

        self.fields["shipping_address"].widget.attrs.update(
            {"class": "form-control mb-2 account-form",
                "placeholder": "Tu dirección de envío"}
        )
        self.fields["billing_address"].required = False
        self.fields["billing_address"].widget.attrs.update(
            {"class": "form-control mb-2 account-form",
                "placeholder": "Dirección de tu oficina (opcional)"}
        )
        self.fields["ciudad"].widget.attrs.update(
            {"class": "form-control mb-2 account-form", "placeholder": "Tu ciudad"}
        )
        self.fields["departamento"].widget.attrs.update(
            {"class": "form-control mb-2 account-form",
                "placeholder": "Tu departamento"}
        )
        self.fields["zip"].widget.attrs.update(
            {"class": "form-control mb-2 account-form",
                "placeholder": "Código Postal"}
        )


class UserEditAccountForm(forms.ModelForm):

    email = forms.EmailField(
        label='Account email and username (can not be changed)', max_length=200, widget=forms.EmailInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'email', 'id': 'form-email', 'readonly': 'readonly'}))

    username = forms.CharField(
        label='Username', min_length=4, max_length=50, widget=forms.TextInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'Username', 'id': 'form-username', 'readonly': 'readonly'}))

    first_name = forms.CharField(
        label='First name', min_length=4, max_length=50, widget=forms.TextInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'Firstname', 'id': 'form-firstname'}))

    last_name = forms.CharField(
        label='Last Name', min_length=4, max_length=50, required=False, widget=forms.TextInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'Lastname', 'id': 'form-lastname'}))

    class Meta:
        model = UserBase
        fields = ('email', 'username', 'first_name', 'last_name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].required = True


GENDER_CHOICE = (
    ('male', 'Hombre'),
    ('female', 'Mujer'),
)


class UserEditProfileForm(forms.ModelForm):

    picture = forms.ImageField(
        label='Profile Picture', required=False, widget=forms.FileInput(
            attrs={'class': 'form-control mb-3', 'id': 'picture-url'}))
    banner = forms.ImageField(
        label='Profile Banner', required=False, widget=forms.FileInput(
            attrs={'class': 'form-control mb-3', 'id': 'banner-url'}))
    url = forms.URLField(
        label='Website Url', max_length=50, required=False, widget=forms.TextInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'Url', 'id': 'form-url'}))
    birthday = forms.DateField(
        label='Birthday', required=False, initial=datetime.date.today, widget=NumberInput(
            attrs={'class': 'form-control mb-3', 'type': 'date', 'id': 'form-birthday'}))
    gender = forms.ChoiceField(
        label='Gender', required=False, choices=GENDER_CHOICE, widget=forms.Select(
            attrs={'class': 'form-control mb-3', 'placeholder': 'Género', 'id': 'form-gender'}))
    bio = forms.CharField(
        label='Bio', min_length=4, max_length=250, required=False, widget=forms.Textarea(
            attrs={'class': 'form-control mb-3', 'rows': 3, 'placeholder': 'Biografía', 'id': 'form-bio'}))
    phone = forms.CharField(
        label='Phone *', min_length=4, max_length=50, widget=forms.TextInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'Phone', 'id': 'form-phone'}))
    mobile = forms.CharField(
        label='Mobile', min_length=4, max_length=50, required=False, widget=forms.TextInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'mobile', 'id': 'form-mobile'}))

    class Meta:
        model = Profile
        fields = ('picture', 'banner', 'url',
                  'birthday', 'gender', 'bio', 'phone', 'mobile',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['phone'].required = True

app/perfiles/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.generic import View

from .forms import UserAddressForm, UserEditAccountForm, UserEditProfileForm
from .models import Address, Profile, UserBase

app_name = "perfiles"


class UserProfileView(View):
    def get(self, request, username, *args, **kwargs):
        user = get_object_or_404(UserBase, username=username)
        profile = Profile.objects.get(user=user)
        addresses = Address.objects.filter(user=user, default=True)

        context = {
            'user': user,
            'profile': profile,
            "addresses": addresses,
        }
        return render(request, 'perfiles/detail.html', context)


@login_required
def edit_profile(request):

    usuario = get_object_or_404(Profile, user=request.user)

    if request.method == 'POST':
        user_form = UserEditAccountForm(
            instance=request.user, data=request.POST)
        profile_form = UserEditProfileForm(
            data=request.POST, files=request.FILES, instance=usuario)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            profile = profile_form.save(commit=False)
            profile.user = user

            profile.save()
            messages.success(
                request,  'Your profile has been successfully updated')
        else:
            messages.error(
                request,  'Your profile can not be updated')
    else:
        user_form = UserEditAccountForm(instance=request.user)
        profile_form = UserEditProfileForm(instance=usuario)

    context = {
        'user_form': user_form,
        'profile_form': profile_form,
        'profile': usuario
    }

    return render(request, 'perfiles/edit_profile.html', context)

# Addresses


@login_required
def view_address(request):
    addresses = Address.objects.filter(user=request.user)
    context = {
        "addresses": addresses,
        "usuario": request.user
    }
    return render(request, "perfiles/addresses.html", context)


@login_required
def add_address(request):
    if request.method == "POST":
        address_form = UserAddressForm(data=request.POST)
        if address_form.is_valid():
            address_form = address_form.save(commit=False)
            address_form.user = request.user
            address_form.save()
            return HttpResponseRedirect(reverse("perfiles:direcciones"))
    else:
        address_form = UserAddressForm()

    profile = Profile.objects.get(user=request.user)
    context = {
        "form": address_form,
        'profile': profile,
    }

    return render(request, "perfiles/edit_addresses.html", context)


@login_required
def edit_address(request, id):
    if request.method == "POST":
        address = Address.objects.get(pk=id, user=request.user)
        address_form = UserAddressForm(instance=address, data=request.POST)
        if address_form.is_valid():
            address_form.save()
            return HttpResponseRedirect(reverse("perfiles:direcciones"))
    else:
        address = Address.objects.get(pk=id, user=request.user)
        address_form = UserAddressForm(instance=address)
    return render(request, "perfiles/edit_addresses.html", {"form": address_form})


@login_required
def delete_address(request, id):
    address = Address.objects.filter(pk=id, user=request.user).delete()
    return redirect("perfiles:direcciones")


@login_required
def set_default(request, id):
    Address.objects.filter(user=request.user,
                           default=True).update(default=False)
    Address.objects.filter(pk=id, user=request.user).update(default=True)
    return redirect("perfiles:direcciones")

app/templates/perfiles/addresses.html
{% extends "base.html" %}
{% block head_title %}Agregar dirección{% endblock %}

{% block content %}
  <div class="container py-3">
    <h1 class="h2">Tus direcciones</h1>
    <div>Administra tus <b>direcciones</b> y preferencias de envío</div>
    <hr />

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    <div class="col">
      <a href="{% url "perfiles:add_address" %}" class="text-reset text-decoration-none" role="button"
        style="max-width: 540px;">
        <div class="card mb-3 h-100" style="border: dashed 2px #ccc;">
          <div class="row g-0 h-100">
            <div class="col-12" style="min-height:100px">
              <div class="card-body text-center position-absolute top-50 start-50 translate-middle">
                <svg style="color:#ccc;" xmlns="http://www.w3.org/2000/svg" width="60" height="60" fill="currentColor"
                  class="bi bi-plus" viewBox="0 0 16 16">
                  <path
                    d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
                </svg>
                <h1 class="h5">Agregar Dirección</h1>
              </div>
            </div>
          </div>
        </div>
      </a>
    </div>
    {% for address in addresses %}
      <div class="col">
        <div class="card pb-3 h-100">
          <div class="card-header bg-light text-primary text-center">
            {% if address.default %}
              <b>Dirección de envío por defecto</b>
            {% endif %}
            &nbsp;
          </div>
          <div class="card-body small pb-1">
            <dl class="row">
              <dt class="col-sm-5">Residencia:</dt>
              <dd class="col-sm-7">
                {{address.shipping_address}}
              </dd>
              {% if address.billing_address %}
                <dt class="col-sm-5">Oficina:</dt>
                <dd class="col-sm-7">
                  {{address.billing_address}}
                </dd>
              {% endif %}
              <dt class="col-sm-5">Ciudad:</dt>
              <dd class="col-sm-7">
                {{address.ciudad}}
              </dd>
              <dt class="col-sm-5">Departamento:</dt>
              <dd class="col-sm-7">
                {{address.departamento}}
              </dd>
              <dt class="col-sm-5">Zip code:</dt>
              <dd class="col-sm-7">
                {{address.zip}}
              </dd>
            </dl>
          </div>
          <div class="card-footer bg-light">
            <a class="btn btn-warning btn-sm text-decoration-none" href="{% url 'perfiles:edit_address' address.id %}">Editar</a>
            <a class="btn btn-danger btn-sm text-decoration-none" href="{% url 'perfiles:delete_address' address.id %}">Eliminar</a>
            {% if not address.default %}
              <a class="btn btn-info btn-sm text-decoration-none" href="{% url 'perfiles:set_default' address.id %}">Por defecto</a>
            {% endif %}
          </div>
        </div>
        </a>
      </div>
    {% endfor %}
  </div>
{% endblock %}

app/templates/perfiles/detail.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load humanize %}

{% block head_title %}
  {% translate "Profile" %} - {{ profile.user.username }}
{% endblock head_title %}

{% block content %}
  <div class="container pb-3 h-100">
    <nav aria-label="breadcrumb" class="pt-2">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">{% translate "Home" %}</a></li>
        <li class="breadcrumb-item"><a href="{% url 'perfiles:perfil' user.username %}">{% translate "User" %}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{profile.user.username}}</li>
      </ol>
    </nav>
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card">
          <div class="rounded-top text-white d-flex flex-row" style="background: url({{profile.banner.url}}) fixed center no-repeat; background-size: cover; height:200px;">
            <div class="ms-4 mt-5 d-flex flex-column" style="width: 150px;">
              <img src="{{profile.picture.url}}" alt="{{profile.user.username}} Profile Picture" class="img-fluid img-thumbnail mt-4 mb-2" style="width: 150px; z-index: 1">
              <a class="btn btn-outline-dark" href="{% url 'perfiles:edit_profile' %}" data-mdb-ripple-color="dark" style="z-index: 1;">
                Edit profile
              </a>
            </div>
            <div class="ms-3" style="margin-top: 130px;">
              <h5>{{profile.user.username}}</h5>
              {% if profile.verified == "verified" %}
                <p>Verificado</p>
              {% else %}
              <p>No Verificado</p>
              {% endif %}

            </div>
          </div>
          <div class="p-4 text-black" style="background-color: #f8f9fa;">
            <div class="d-flex justify-content-end text-center py-1">
              <div>
                <p class="mb-1 h5">253</p>
                <p class="small text-muted mb-0">Photos</p>
              </div>
              <div class="px-3">
                <p class="mb-1 h5">1026</p>
                <p class="small text-muted mb-0">Followers</p>
              </div>
              <div>
                <p class="mb-1 h5">478</p>
                <p class="small text-muted mb-0">Following</p>
              </div>
            </div>
          </div>
          <div class="card-body p-4 text-black">
            <div class="mb-5">
              <p class="lead fw-normal mb-1">Información</p>
              {% if profile.bio %}
                <div class="p-4" style="background-color: #f8f9fa;">
                  <p class="text-muted font-italic mb-1">{{profile.bio}}</p>
                </div>
              {% else %}
                <div class="p-4" style="background-color: #f8f9fa;">
                  <p class="text-muted font-italic mb-1">Información no disponible</p>
                </div>
            </div>
            {% endif %}

            <div class="d-flex justify-content-between align-items-center mb-3">
              <p class="lead fw-normal mb-1">Datos de la cuenta</p>
              <p class="mb-0"><a href="#!" class="text-muted small">Necesito ayuda</a></p>
            </div>
            <div class="p-3" style="background-color: #f8f9fa;">
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Nombre</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">
                    {% filter upper %}
                      {{ profile.user.first_name }} {{ profile.user.last_name }}
                    {% endfilter %}
                  </p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Usuario</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{profile.user.username}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Email</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{profile.user.email}}</p>
                </div>
              </div>
            </div>
            <div class="d-flex justify-content-between align-items-center mt-4 mb-3">
              <p class="lead fw-normal mb-0">Datos Personales</p>
              <p class="mb-0"><a href="#!" class="text-muted small">Necesito ayuda</a></p>
            </div>
            <div class="p-3" style="background-color: #f8f9fa;">
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Teléfono</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{ profile.phone }}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Celular</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{ profile.mobile }}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Dirección</p>
                </div>
                <div class="col-sm-9">
                  {% for addr in addresses %}
                    <p class="text-muted mb-0">{{ addr.shipping_address }}</p>
                  {% endfor %}
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Tipo de Dirección</p>
                </div>
                <div class="col-sm-9">
                  {% for addr in addresses %}
                    <p class="text-muted mb-0">{{ addr.address_type }}</p>
                  {% endfor %}
                </div>
              </div>
              <hr>
            </div> <!-- /div .p-3 -->
          </div> <!-- /div .card-body -->
        </div> <!-- /div .card -->
      </div> <!-- /div .col -->
    </div> <!-- /div .row -->
  </div> <!-- /div .container -->
{% endblock content %}

app/templates/perfiles/edit_addresses.html
{% extends "base.html" %}
{% block head_title %}Crear-Editar dirección{% endblock %}

{% block content %}
<div class="container py-3">
      <form name="address_form" class="account-form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
          <div class="col-8 mx-auto">
            <h1 class="h3">Crear/Editar Dirección</h1>
            <div>Agregue o edite una <b>dirección</b> de envío</div>
            <hr />
            {% if form.errors %}
              <div class="alert alert-primary" role="alert">
                Error: Por favor trate nuevamente!
              </div>
            {% endif %}
            <div class="mb-3">
              <label for="direccionResidencia" class="form-label">{{ form.shipping_address.label}}</label>
                {{ form.shipping_address }}
            </div>
            <div class="mb-3">
              <label class="form-label">{{ form.billing_address.label}}</label>
                {{ form.billing_address }}
            </div>
            <div class="mb-3">
              <label class="form-label">{{ form.ciudad.label}}</label>
              {{ form.ciudad }}
            </div>
            <div class="mb-3">
              <label class="form-label">{{ form.departamento.label}}</label>
              {{ form.departamento }}
            </div>
            <div class="mb-3">
              <label class="form-label">{{ form.zip.label}}</label>
              {{ form.zip }}
            </div>
            <button class="btn btn-primary btn-block py-2 mb-4 mt-4 fw-bold w-100" type="button" value="Submit" onclick="submitForm()">
            Agregar dirección
            </button>
          </div>
        </div>
      </form>
</div>

<script>
function submitForm() {
   var form = document.getElementsByName('address_form')[0];
   form.submit(); // Submit the form
   form.reset();  // Reset all form data
   return false; // Prevent page refresh
}
</script>
{% endblock %}

app/templates/perfiles/edit_profile.html
{% extends "base.html" %}
{% load i18n %}

{% block head_title %}
  {% translate "Edit Profile" %} - {{ profile.user.username }}
{% endblock head_title %}

{% block content %}
  <style>
    .account-form input {
        border: 2px solid #ccc;
        height: calc(2em + .75rem + 2px);
    }

    .account-form input:focus {
        border-color: #1497ff;
        box-shadow: none;
    }
  </style>


  <div class="container">
    <div class="row">
      <div class="col-12 col-lg-7  mx-auto">

        <form class="account-form px-4 pt-4" method="post" enctype="multipart/form-data">

          {% if profile_form.is_valid %}
            <div class="alert alert-primary" role="alert">
              Profile successfully updated!
            </div>
            <p class="small text-center pt-0">
              <a href="{% url "perfiles:perfil" user.username %}">Back to Profile</a>
            </p>
          {%else%}
            <h3>Change your details</h3>
            <p>You can edit your account using the following form:</p>
          {% endif %}

          {% if profile_form.errors %}
            <div class="alert alert-primary" role="alert">
              {% for field in profile_forms %}
                {% for error in field.errors %}
                  {{ error|escape }}
                {% endfor %}
              {% endfor %}
              {% for error in profile_form.non_field_errors %}
                {{ error|escape }}
              {% endfor %}
              Error: Please try again!
            </div>
          {% endif %}

          {% csrf_token %}
          <label class="small font-weight-bold">{{ user_form.email.label }}</label>
          {{ user_form.email }}
          <label class="small font-weight-bold">{{ user_form.username.label }}</label>
          {{ user_form.username }}
          <label class="small font-weight-bold">{{ user_form.first_name.label }}</label>
          {{ user_form.first_name }}
          <label class="small font-weight-bold">{{ user_form.last_name.label }}</label>
          {{ user_form.last_name }}

          <label class="small font-weight-bold">{{ profile_form.picture.label }}</label>
          {{ profile_form.picture }}
          <label class="small font-weight-bold">{{ profile_form.banner.label }}</label>
          {{ profile_form.banner }}
          <label class="small font-weight-bold">{{ profile_form.url.label }}</label>
          {{ profile_form.url }}
         <label class="small font-weight-bold">{{ profile_form.birthday.label }}</label>
          {{ profile_form.birthday }}
          <label class="small font-weight-bold">{{ profile_form.gender.label }}</label>
          {{ profile_form.gender }}
          <label class="small font-weight-bold">{{ profile_form.bio.label }}</label>
          {{ profile_form.bio }}
          <label class="small font-weight-bold">{{ profile_form.phone.label }}</label>
          {{ profile_form.phone }}
          <label class="small font-weight-bold">{{ profile_form.mobile.label }}</label>
          {{ profile_form.mobile }}

          <input id='form-button' class="btn btn-primary btn-block py-2 mb-4 mt-5 fw-bold w-100" type="submit"
              value="Guardar Cambios"></input>
          <hr class="mb-3">
        </form>
      </div>
    </div>
  </div>

{% endblock %}