app/cart/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name='cart_detail'),
    path('increase-quantity/<pk>/',
         views.IncreaseQuantityView.as_view(), name='increase-quantity'),
    path('decrease-quantity/<pk>/',
         views.DecreaseQuantityView.as_view(), name='decrease-quantity'),
    path('remove-from-cart/<pk>/',
         views.RemoveFromCartView.as_view(), name='remove-from-cart'),
    path('checkout/', login_required(views.CheckoutView.as_view()), name='checkout'),
    path('payment/', login_required(views.PaymentView.as_view()), name='payment'),
    path('thanks/', views.ThankYouView.as_view(), name='thanks'),
]

app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('users/', include('perfiles.urls', namespace='perfiles')),
    path('products/', include('products.urls', namespace='products')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/perfiles/urls.py
from django.contrib.auth import views
from django.urls import path

from . import views
from .views import UserProfileView

app_name = "perfiles"

urlpatterns = [
    path("addresses/", views.view_address, name="direcciones"),
    path("add_address/", views.add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"),
    path("addresses/delete/<slug:id>/",
         views.delete_address, name="delete_address"),
    path("addresses/set_default/<slug:id>/",
         views.set_default, name="set_default"),
    path("edit_profile/", views.edit_profile, name="edit_profile"),
    path('<username>/', UserProfileView.as_view(), name="perfil")
]

app/products/urls.py
from django.urls import path

from .views import ProductListView, MediaDetailView

app_name = "products"

urlpatterns = [
    path("<int:pk>", MediaDetailView.as_view(), name="media_detail"),
    path("", ProductListView.as_view(), name="products"),
]

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />

    <!-- Majestic style from Bootstrap5 -->
    <link rel="stylesheet" href="{% static 'css/theme.min.css' %}" />
    <!--  Bootstrap5 -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <!-- MDB icon -->
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon" />
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}" />
    <!-- custom css styles-->
    <link rel="stylesheet" href="{% static 'css/user.css' %}" />
    <!-- Google Fonts Roboto -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap"
    />
    <!-- MDB -->
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}" />
    <title>
    {% block head_title %}sproj4{% endblock head_title %}
    </title>
    {% block extra_head %}{% endblock extra_head %}
  </head>
  <header>
  {% include 'top_nav.html' %}
  {% include 'middle_nav.html'%}
  </header>
  <body>
    <main style="background-color:#ebebeb;">
      {% block content %}
      {% endblock content %}
    </main>

    {% include 'footer.html' %}

    <!-- MDB -->
    <script type="text/javascript" src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/feather.min.js' %}"></script>

    {% block scripts %}{% endblock scripts %}

    <!-- Custom scripts -->
    <script type="text/javascript">
      feather.replace();
    </script>
  </body>
</html>

app/templates/carousel.html
{% load static %}
<div
  id="carouselDarkVariant"
  class="carousel slide carousel-fade carousel-dark"
  data-mdb-ride="carousel"
>

  <!-- Inner -->
  <div class="carousel-inner">
    <!-- Single item -->
    <div class="carousel-item active">
      <img
        src="{% static 'img/slides/img01.webp' %}"
        class="d-block w-100"
        alt="..."
      />
    </div>

    <!-- Single item -->
    <div class="carousel-item">
      <img
        src="{% static 'img/slides/img02.webp' %}"
        class="d-block w-100"
        alt="..."
      />
    </div>

    <!-- Single item -->
    <div class="carousel-item">
      <img
        src="{% static 'img/slides/img03.webp' %}"
        class="d-block w-100"
        alt="..."
      />
    </div>
  </div>
  <!-- Inner -->

  <!-- Controls -->
  <button
    class="carousel-control-prev"
    type="button"
    data-mdb-target="#carouselDarkVariant"
    data-mdb-slide="prev"
  >
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button
    class="carousel-control-next"
    type="button"
    data-mdb-target="#carouselDarkVariant"
    data-mdb-slide="next"
  >
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/templates/categories.html
{% extends 'base.html' %}

{% load static %}
{% load i18n %}
{% load humanize %}

{% block head_title %}
  {% if user.is_authenticated %}
    {% translate "Home" %} - {{ user.get_username }}
  {% else %}
    {% translate "Home" %}
  {% endif %}
{% endblock head_title %}

{% block left_sidebar %}
  {% include 'components/sidebars/left/sidebar.html' %}
{% endblock left_sidebar %}

{% block content %}
  <main style="background-color:#eee;">
    <!-- Carousel wrapper -->
    {% include 'carousel.html' %}
    <!-- Carousel wrapper -->

    <section style="background-color: #eee;">
      <div class="container py-5">
      <div class="d-flex justify-content-start align-items-center">
          <h2>{{ category.name}}</h2>
          <a class="mx-3" href="/">Todas las Categorías</a>
        </div>
        <div class="row">
          {% for post in posts %}
            <div class="col-md-6 col-lg-3 mb-4">
              <div class="card h-100">
                <div class="d-flex justify-content-between p-3">
                  <p class="lead mb-0">Oferta Por Combo</p>
                  <div
                    class="bg-info rounded-circle d-flex align-items-center justify-content-center shadow-1-strong"
                    style="width: 35px; height: 35px;"
                  >
                    <p class="text-white mb-0 small">x4</p>
                  </div>
                </div>
                <a href="{{ post.get_absolute_url }}">
                  <img
                    src="{{ post.image.image.url }}"
                    class="card-img-top"
                    alt="{{ post.image.alt_text }}"
                    style="height:207px"
                  />
                </a>
                <div class="card-body">
                  <div class="d-flex justify-content-between">
                    <p class="small">
                      <a href="#!" class="text-muted">{{ post.inventory.product_type }}</a>
                    </p>
                    {% if post.inventory.discount_price %}
                    <p class="small text-danger">
                      <s>${{ post.inventory.store_price|intcomma }}</s>
                    </p>
                    {% endif %}
                  </div>

                  <div class="d-flex justify-content-between mb-3">
                    <a href="{{ post.get_absolute_url }}" class="text-decorations-none">
                      <h5 class="mb-0">{{ post.title }}</h5>
                    </a>
                    {% if post.inventory.discount_price %}
                      <h5 class="text-dark mb-0">${{ post.inventory.discount_price|intcomma }}</h5>
                    {% else %}
                      <h5 class="text-dark mb-0">${{ post.inventory.store_price|intcomma }}</h5>
                    {% endif %}
                  </div>

                  <div class="d-flex justify-content-between mb-2">
                    <p class="text-muted mb-0">Disponibles: <span class="fw-bold">6</span></p>
                    <div class="ms-auto text-warning">
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
        </div> <!-- /row -->
      </div>
    </section>
  </main>
{% endblock content %}

app/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load crispy_forms_tags %}

{% load i18n %}
{% block head_title %}

  {{ post.product.name }}
  {% if user.is_authenticated %}
    - {{ user.username }}
  {% endif %}
{% endblock head_title %}

{% block content %}
  <div class="container dark-grey-text pt-3">
    <div class="row d-flex justify-content-center wow fadeIn">
      <div class="card ml-10" style="">
        <div class="row g-0">
          <div class="col-md-5 d-flex justify-content-end">
            <img
              src="{{post.img.url}}"
              alt="{{post.alt_text}}"
              class="img-fluid"
            />
          </div>
          <div class="col-md-7 d-flex align-self-center">
            <div class="card-body">
              <div class="mx-4">
                <a href="#">
                  <span class="badge  bg-warning mr-1">
                    {% for category in post.product.category.all %}
                        {{ category }}
                    {% endfor %}
                  </span>
                  <span class="badge  bg-{{ item.get_label_display }} bg-danger">
                    {% translate "NEW" %}
                  </span>
                </a>
                <p class="lead">
                  {% if post.product.discount_price %}
                  <span class="me-3">
                    <del>${{ post.product.store_price|intcomma }}</del>
                  </span>
                  <span>${{ post.product.discount_price|intcomma }}</span>
                  {% else %}
                  <span>${{ post.product.store_price|intcomma }}</span>
                  {% endif %}
                </p>

                <h5 class="card-title">{% translate "Description" %}</h5>
                <p class="card-text">
                  {{ post.product.description }}
                </p>
                {% comment %} <form action="{% url 'cart:cart_add' post.id %}" method="POST"> {% endcomment %}
                <form action="" method="POST">
                  {% csrf_token %}
                  {{ form|crispy }}
                  {% comment %} {{ cart_product_form|crispy }} {% endcomment %}
                  <input type="submit" class="btn btn-primary btn-md my-0 p" value="{% translate "Agregar al carrito" %}">
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <hr>

    <div class="row d-flex justify-content-center wow fadeIn">
      <div class="col-md-6 text-center">
        <h4 class="my-4 h4">Additional information</h4>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
          voluptates,
          quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>
      </div>
    </div>
    <div class="row">
      {% for image in images %}
        <div class="col-md-6 col-lg-4 mb-4">
          <div class="card-group h-100">
            <div class="card">
              <img src="{{ image.image.url }}" class="card-img-top" alt="{{ image.alt_text }}">
              <div class="card-body">
                <h5 class="card-title">{{ image.product.name }}</h5>
                <p class="card-text">{{ image.product.description }}</p>
                <p class="card-text"><small class="text-muted">{{ image.product.brand }}</small></p>
              </div>
            </div>
          </div>
        </div>


        {% comment %} <div class="col-lg-4 col-md-12 mb-4">
          <div class="card h-100">
            <img src="{{ image.image.url }}" class="img-fluid" alt="{{ image.alt_text }}">
          </div>
        </div> {% endcomment %}
      {% endfor %}
    </div>
  </div>
{% endblock content %}

app/templates/footer.html
{% load static %}
{% load i18n %}
<div class="container">
  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted"> {% translate "Home" %} </a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted"> {% translate "Features" %} </a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted"> {% translate "Pricing" %} </a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted"> {% translate "FAQs" %} </a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted"> {% translate "About" %} </a></li>
    </ul>
    <p class="text-center text-muted">
        &copy; {% now "Y" %}
        {% translate "All rights reserved - This website is made with" %}
        <i class="fa fa-heart"></i>
    </p>
  </footer>
</div>

app/templates/middle_nav.html
{% load static %}
{% load i18n %}
{% load mptt_tags %}

<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light mt-7">
    <div class="justify-content-between">
      <button
        class="navbar-toggler"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#navbarTogglerCat"
        aria-controls="navbarTogglerCat"
        aria-expanded="false"
        aria-label="Toggle navigation"
        >
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerCat">
        <a class="navbar-brand" href="#">Categorías:</a>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
         {% recursetree categories %}
            {% if node.is_leaf_node %}
              <li class="nav-item">
                <a class="nav-link" href="{{ node.get_absolute_url }}">{{ node.name|title }}</a>
              </li>
            {% else %}
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="{{ node.get_absolute_url }}"
                  id="navbarDropdown"
                  role="button"
                  data-mdb-toggle="dropdown"
                  aria-expanded="false">
                  {{ node.name }}
                </a>

                  <ul class="children dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{{ node.get_absolute_url }}">
                      {{ children }}
                    </a>
                  </ul>
              </li>
            {% endif %}
          {% endrecursetree %}
        </ul>

        <div class="d-flex align-items-end">
          <form class="d-flex input-group">
            {% csrf_token %}
              <input
                type="search"
                class="form-control rounded"
                placeholder="Search"
                aria-label="Search"
                aria-describedby="search-addon"
              />
              <span class="input-group-text border-0 d-flex align-self-center" id="search-addon">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                  <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                </svg>
              </span>
          </form>
        </div>
        <span>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt" viewBox="0 0 16 16">
            <path d="M12.166 8.94c-.524 1.062-1.234 2.12-1.96 3.07A31.493 31.493 0 0 1 8 14.58a31.481 31.481 0 0 1-2.206-2.57c-.726-.95-1.436-2.008-1.96-3.07C3.304 7.867 3 6.862 3 6a5 5 0 0 1 10 0c0 .862-.305 1.867-.834 2.94zM8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10z"/>
            <path d="M8 8a2 2 0 1 1 0-4 2 2 0 0 1 0 4zm0 1a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
</svg>
        </span>dirección de envío
      </div>
    </div>
  </nav>
</div>

app/templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Anterior</a>
    {% endif %}
    <span class="current">
    Pag {{ page.number }} de {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
      <a href="?page={{ page.next_page_number }}">Siguiente</a>
    {% endif %}
  </span>
</div>

app/templates/top_nav.html
{% load static %}
{% load cart_template_tags %}
{% load i18n %}
<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3 d-block" data-navbar-on-scroll="data-navbar-on-scroll" style="background-color: #e3f2fd;">
  <div class="container">
    <a class="navbar-brand d-inline-flex" href="/">
      <img class="d-inline-block" src="{% static 'img/logo1.png' %}" alt="Logo" />
      <span class="text-1000 fs-0 fw-bold ms-2">Sproj-4</span>
    </a>
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>

    <div class="collapse navbar-collapse border-top border-lg-0 mt-4 mt-lg-0" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item px-2">
          <a class="nav-link fw-medium active" aria-current="page" href="{% url 'products:products' %}">
            Productos
          </a>
        </li>
      </ul>
      <!-- right side-->
      {% if request.user.is_authenticated %}
        <form class="d-flex">
          {% csrf_token %}

          <a
            class="dropdown-toggle d-flex align-items-center hidden-arrow"
            href="#"
            id="navbarDropdownMenuLink"
            role="button"
            data-mdb-toggle="dropdown"
            aria-expanded="false">
            <img
              src="{{ user.profile.picture.url }}"
              class="rounded-circle me-1"
              height="25"
              alt=""
              loading="lazy"
            />
            <span class="text-muted me-3">{{ user.username }}</span>
          </a>
          <ul
            class="dropdown-menu dropdown-menu-end me-10"
            aria-labelledby="navbarDropdownMenuLink">
            <li>
              <a class="dropdown-item" href="{% url 'perfiles:perfil' user.username %}">{% translate "My profile" %}</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">{% translate "Settings" %} &raquo;</a>
              <ul class="dropdown-menu dropdown-submenu">
                <li>
                  <a class="dropdown-item" href="{% url 'perfiles:edit_profile' %}">{% translate "Edit Profile" %}</a>
                </li>
                <li>
                  <a class="dropdown-item" href="{% url 'perfiles:direcciones' %}">{% translate "Add address" %}</a>
                </li>
                <li>
                  <a class="dropdown-item" href="#">Submenu item 3 &raquo; </a>
                  <ul class="dropdown-menu dropdown-submenu">
                    <li>
                      <a class="dropdown-item" href="#">Multi level 1</a>
                    </li>
                    <li>
                      <a class="dropdown-item" href="#">Multi level 2</a>
                    </li>
                  </ul>
                </li>
              </ul>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'account_logout' %}">{% translate "Log out" %}</a>
            </li>
          </ul>
          <a class="text-1000" href="{% url 'cart:cart_detail' %}">
            <span class="badge badge-pill bg-danger">{{ request|cart_item_count }}</span>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart me-3"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg>
          </a>
          <a
            class="text-reset me-3 dropdown-toggle hidden-arrow"
            href="#"
            id="navbarDropdownMenuLink"
            role="button"
            data-mdb-toggle="dropdown"
            aria-expanded="false">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bell"><path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"></path><path d="M13.73 21a2 2 0 0 1-3.46 0"></path></svg>
            <span class="badge rounded-pill badge-notification bg-danger">1</span>
          </a>
          <ul
            class="dropdown-menu dropdown-menu-end"
            aria-labelledby="navbarDropdownMenuLink">
            <li>
              <a class="dropdown-item" href="#">Some news</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Another news</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Something else here</a>
            </li>
          </ul>
          <a class="text-1000" href="/">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-phone me-3"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path></svg>
          </a>
          <a class="text-1000" href="#!">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search me-3"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>
          </a>
          <a class="text-1000" href="#!">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-heart me-3"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path></svg>
          </a>
        </form>
      {% else %}
        <form class="d-flex">
          {% csrf_token %}
          <a class="text-1000" href="{% url 'cart:cart_detail' %}">
            <span class="badge badge-pill bg-danger">{{ request|cart_item_count }}</span>
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shopping-cart me-3"><circle cx="9" cy="21" r="1"></circle><circle cx="20" cy="21" r="1"></circle><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"></path></svg>
          </a>
          <a class="text-1000 me-3" href="/">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bell"><path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"></path><path d="M13.73 21a2 2 0 0 1-3.46 0"></path></svg>
          </a>
          <a class="text-1000" href="/">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-phone me-3"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path></svg>
          </a>
          <a class="text-1000" href="/">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search me-3"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>
          </a>
          <a class="text-1000" href="/">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-heart me-3"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path></svg>
          </a>
          <a
            class="dropdown-toggle d-flex align-items-center text-1000 hidden-arrow"
            href="#"
            id="navbarDropdownMenuLink"
            role="button"
            data-mdb-toggle="dropdown"
            aria-expanded="false">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user me-3"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
          </a>
          <ul
            class="dropdown-menu dropdown-menu-end"
            aria-labelledby="navbarDropdownMenuLink">
            <li>
              <a class="dropdown-item" href="{% url 'account_login' %}">{% translate "Log in" %}</a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'account_signup' %}">{% translate "Sign up" %}</a>
            </li>
          </ul>
        </form>
      {% endif %}
    </div>
  </div>
</nav>